set(CMAKE_SYSTEM_NAME      Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(QCDX_TARGET_TRIPLE x86_64-linux-gnu)

find_program(CMAKE_C_COMPILER   ${QCDX_TARGET_TRIPLE}-gcc     REQUIRED)
find_program(CMAKE_CXX_COMPILER ${QCDX_TARGET_TRIPLE}-g++     REQUIRED)
find_program(CMAKE_AR           ${QCDX_TARGET_TRIPLE}-gcc-ar)
find_program(CMAKE_RANLIB       ${QCDX_TARGET_TRIPLE}-gcc-ranlib)
find_program(CMAKE_STRIP        ${QCDX_TARGET_TRIPLE}-strip)
find_program(CMAKE_OBJCOPY      ${QCDX_TARGET_TRIPLE}-objcopy)

if(CMAKE_SYSROOT)
  list(APPEND CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
