# Version check for find_package(QCDX ...). Before 1.0 a minor release may
# break things, so 0.1 matches 0.1.x only; from 1.0 the major version decides.
# Version ranges (find_package(QCDX 0.1...<0.3)) are checked against the bounds.

file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/projectkit/VERSION" PACKAGE_VERSION LIMIT_COUNT 1)

set(PACKAGE_VERSION_COMPATIBLE FALSE)
set(PACKAGE_VERSION_EXACT FALSE)

if(PACKAGE_FIND_VERSION_RANGE)
  set(_qcdx_ok TRUE)
  if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION_MIN)
    set(_qcdx_ok FALSE)
  endif()
  if(PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "INCLUDE")
    if(PACKAGE_VERSION VERSION_GREATER PACKAGE_FIND_VERSION_MAX)
      set(_qcdx_ok FALSE)
    endif()
  elseif(PACKAGE_VERSION VERSION_GREATER_EQUAL PACKAGE_FIND_VERSION_MAX)
    set(_qcdx_ok FALSE)
  endif()
  set(PACKAGE_VERSION_COMPATIBLE ${_qcdx_ok})
  unset(_qcdx_ok)
elseif(NOT PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
elseif(PACKAGE_VERSION VERSION_GREATER_EQUAL PACKAGE_FIND_VERSION)
  string(REGEX MATCH "^[0-9]+" _qcdx_major "${PACKAGE_VERSION}")
  string(REGEX MATCH "^[0-9]+\\.[0-9]+" _qcdx_minor "${PACKAGE_VERSION}")
  if(_qcdx_major STREQUAL "0")
    set(_qcdx_have "${_qcdx_minor}")
    set(_qcdx_want "${PACKAGE_FIND_VERSION_MAJOR}.${PACKAGE_FIND_VERSION_MINOR}")
  else()
    set(_qcdx_have "${_qcdx_major}")
    set(_qcdx_want "${PACKAGE_FIND_VERSION_MAJOR}")
  endif()
  if(_qcdx_have STREQUAL _qcdx_want)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  endif()
  if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
  unset(_qcdx_major)
  unset(_qcdx_minor)
  unset(_qcdx_have)
  unset(_qcdx_want)
endif()
